### ISSUE TITLE
Split C and Perl

### ISSUE THREAD

**Issue by livibetter** [pipeseroni/pipes.c#1]
@OneLastTry maybe we should split them, create another repository for `snakes.pl`?

Remove `snakes.pl` from commits and forced update, and extract it and `LICENSE` for its own repository. Since currently we have no GitHub forks, it could be a good time to do it if we want to.

Do you think this is a good idea?

If you think so, I'd hope you'd take on this, and take the chance to update `README` after the extraction completed.

**Comment by StefansM** [comment]
I think you're right. There's no reason to keep them together, particularly with an organisation for collating them. I've created the repository [snakes.pl](https://github.com/pipeseroni/snakes.pl) and removed `snakes.pl` from the "snakes" repository.
