### ISSUE TITLE
Support all colours in the terminal

### ISSUE THREAD

**Issue by StefansM** [pipeseroni/pipes.c#10]
At the moment, we use `COLORS` (i.e. the max available) colours, but don't actually initialise any to anything beyond the default values. We should take advantage of all available colours (the max. number of colours should be configurable). An HSL to RGB converter will let us pick colours that look good on a dark (or light) background and span the colours nicely.

Following from that, the background colour for the pipes should be configurable and default to the colour used by terminal (i.e. call the ncurses extension `use_default_colors` and default passing `-1` to `init_pair`). If the background is dark, the default pipe colours should be light and vice-versa.

**Comment by livibetter** [comment]
Wait for [ncurses support for 24-bit](https://gist.github.com/XVilka/8346728#gistcomment-2356008), go all the way up to the top?

I'd thought about to add true color to pipes.sh, but it won't be easy as a few options are fixed to the 16-color, that's a big clash.  I'd like to see a pipe crawling and gradually increasing color value and decreasing after a turn.  I'm sure pipes.sh v24.0.0 would have it. :laughing:

**Comment by StefansM** [comment]
I had no idea 24-bit colour was available on most terminals! I've been sitting here in the dark ages with urxvt. The recent 6.1 release of ncurses makes it more readily available: ![24-bit colour in a terminal](https://user-images.githubusercontent.com/396334/36634175-6b68822c-1998-11e8-84b9-a3a1173b1130.png)

That image is of *xterm*, which blows my mind. The API is weird and poorly documented, and it takes 0.6 seconds to render that 19,040-character frame, but it's still cool. It's possible I'm misunderstanding the API and doing something wrong to slow it down: I'm not sure.

**Comment by livibetter** [comment]
:rainbow_flag: Let's bring the Nyan :cat2: in!  /jk

I only re-read that link--to do some [revamp](https://github.com/lbgists/blue-ocean)--in my previous comment to discover I already have the st ready for 24-bit, after I updated tmux and ran the sample Bash code, I was like :astonished:.

![2018-02-25--10 53 01](https://user-images.githubusercontent.com/30909/36637614-d5fc5f6e-1a1a-11e8-97d8-4d4d90065a90.png)
*(tiny font size (forgot to count the characters), code slightly edited to be more eerily smooth)*

I thought, according to that comment, ncurses 6.1 still couldn't don't support 24-bit, only terminfo is updated for the support?  Well, guess you can't completely believe what you read on Internet.

It's much more slower than 256-colors and ASCII, but I am not entirely sure if it's the color, the Unicode seems to be a factor of slowness as well.
