### ISSUE TITLE
Add Travis CI?

### ISSUE THREAD

**Issue by livibetter** [pipeseroni/pipes.c#2]
To ensure any PR can be compiled without issues.

Few notes:

* Turn on `-Werror`, so the build would fail on a single warning.
* Wishlist:
  * Also do `CC=clang`.
  * We can also add OS X, although I don't think the Makefile can work as it uses `pkg-config` and I don't know how that will go on Mac.

Thoughts and takers, if @StefansM approves this.

**Comment by StefansM** [comment]
I have no objection to this. I've no experience with Travis, but what better way to learn than on a nice simple project? I'll try it on a fork so I don't clutter the repo with lots of broken `.travis.yml` files.

**Comment by livibetter** [comment]
@StefansM Since you have multiple issue opened, I think you might be busy working on them, mind if I take this one, if you are not already reading the Travis docs.  I think this would be nice to get this done early, although it doesn't matter that much when we only have you do actual coding.

**Comment by StefansM** [comment]
@livibetter Please feel free, the more checks we have the better.

**Comment by StefansM** [comment]
Sorted in #15
