### ISSUE TITLE
Cant install pipes.c

### ISSUE THREAD

**Issue by Mia75owo** [pipeseroni/pipes.c#35]
When i run
```
autoreconf -i
./configure && make && make install
```
I get this error:
```
./configure: line 4631: syntax error near unexpected token `dash-version'
./configure: line 4631: `AX_IS_RELEASE(dash-version)'
```

**Comment by Efreak** [comment]
I'm getting this too

**Comment by Mia75owo** [comment]
I think this got fixed just download the newest version and try again.

**Comment by Efreak** [comment]
I'm getting this *now* with the current version. There's been no commits since 2018. Reading the readme, I'm guessing it's related to autoconf-archive, which isn't available to me in termux, and the necessary dependencies to build it are also not available.
