### ISSUE TITLE
Name of binrary and/or the project

### ISSUE THREAD

**Issue by livibetter** [pipeseroni/pipes.c#4]
The #3 makes me think about the installed binary, `snake` might conflict with others, a search with "snake" on [Portage File List](http://www.portagefilelist.de/site/start) (an installed files search engine for Gentoo Portage) showed two potential conflicts:

* `dev-lang/nwcc`: `/usr/nwcc/bin/snake`
* `games-misc/bsd-games`: `/usr/games/bin/snake`

Never heard of nwcc, but bsd-games is enough.  Another quick search for "snakes" returned zero results.  It is not a filepath conflict, but `PATH` search issue.

And if we are going to submit this to package directory, this would have to be fixed, even this might be allowed as long as no one else is installed at `/usr/bin/snake`, although we might need to install under `/usr/games` depending on the rules of the directory.

I can see a few solutions:

* Rename the binary/source to `snakes`?
* Prefix/append some extra string to `snake` for the binary?
* Rename entirely?
* Others?

**Comment by StefansM** [comment]
I kind of think the repository should be renamed `pipes.c` to better fit the current naming convention. If we do that, `pipes` makes sense as a binary name, and doesn't conflict with any binaries according to the portage file list.

**Comment by livibetter** [comment]
I like `pipes.c`, and if there is no other names and/or objections, I will rename the repo to it.  (Well, somebody has to do `s/snakes?/pipes.c/gi`)

**Comment by livibetter** [comment]
I like `pipes.c`, and if there is no other names and/or objections, I will rename the repo to it in 7 days.  (Well, somebody has to do `s/snakes?/pipes.c/gi`)

**Comment by livibetter** [comment]
@StefansM Could you check repo Settings?  I think you might be able to rename it, GitHub docs doesn't mention that.  If you can, I think you should be the one to rename this repo.

**Comment by StefansM** [comment]
Changes to code made in #13 -- renaming repository now.
