### ISSUE TITLE
Add versioning

### ISSUE THREAD

**Issue by livibetter** [pipeseroni/pipes.c#7]

**Comment by StefansM** [comment]
When we agree on a build system, I'll tag a 1.0.0 release. There is plenty of work to do, but this project has sat for years in its current state and #5 fixed most bugs that don't require big changes, so I think 1.0.0 makes sense.

**Comment by livibetter** [comment]
@StefansM I can't wait for that big 1.  I am not sure what issues you plan to resolve before tagging it, perhaps you can use Projects or Milestone to track the progress.  And 1.0.0 would be released as pipes.c (#4), right?

**Comment by StefansM** [comment]
Hooray! [Version 1.0.0](https://github.com/pipeseroni/pipes.c/releases/tag/v1.0.0) has been released.
